packaging_format = 2

id = "emojiwall"
name = "Owncast Emoji Wall"
description.en = "The emoji wall (also known as a \"on-screen emotes overlay\") takes the emojis and custom emotes sent in the chat of Owncast streamers and displays them bubbling up the screen!"

version = "1.1.2"

maintainers = ["the7thNightmare"]

[upstream]
license = "AGPL-3.0"
code = "https://framagit.org/owncast-things/owncast-emojiwall"
website = "https://smol.stream/emojiwall"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/emojiwall"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://framagit.org/owncast-things/owncast-emojiwall/-/archive/v1.1.2/owncast-emojiwall-v1.1.2.tar.gz"
        sha256 = "e82834ace3b99d162d9bcc37babf9ededff1f29d9871df239cd05211d5882197"
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ""
