packaging_format = 2

id = "owncast-emojiwall"
name = "Emojiwall for Owncast"
description.en = "Emojiwall (on-screen emotes overlay) for Owncast"
description.fr = "Emojiwall (superposition d'émoticônes à l'écran) pour Owncast"
description.id = "Dinding emoji (tayangan emoji dalam layar) untuk Owncast"

version = "1.1.4~ynh2"

maintainers = ["the7thNightmare"]

[upstream]
license = "MIT"
website = "https://smol.stream/emojiwall"
code = "https://framagit.org/owncast-things/owncast-emojiwall"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/emojiwall"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://framagit.org/owncast-things/owncast-emojiwall/-/archive/v1.1.4/owncast-emojiwall-v1.1.4.tar.bz2"
        sha256 = "4e136a7b9091247ee46365645a25bbc0014db89dd175dfe3601b056ff4e0ba11"
        in_subdir = true
        autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
