#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression -m "Stopping the systemd service..." -w 1

ynh_systemd_action -a stop

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression -m "Updating NGINX web server configuration..." -w 1

ynh_change_url_nginx_config

#=================================================
# MODIFY CONFIGURATION
#=================================================

ynh_add_config -t default.json -d "$install_dir/config/default.json"

#=================================================
# GENERIC FINALISATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression -m "Starting the systemd service..." -w 1

ynh_systemd_action -a start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression -m "Change of URL completed for $app" -l
